[log]
path = "logs"
format = "log_%(date)s-%(time)s.txt"
level = 1
enabled = false

[net]
tickrate = 30
port = 1212
bindto = "::,0.0.0.0"
max_connections = 64

[status]
enabled = true
connectaddress = "ss14://vermistdust.space"

[game]
hostname = "Vermist Dust Sector"
lobbyenabled = true
soft_max_players = 32
role_timers = false
desc = "*cough cough* ...it sure is dusty out here."
lobbyduration = 600
# a bit more time to hang out at centcomm
round_restart_time = 240

[ic]
flavor_text = true
restricted_names = false

[ooc]
enable_during_round = true

[looc]
enabled_crit = true

[shuttle]
emergency_early_launch_allowed = true

[infolinks]
github = "https://github.com/vermist-sector/vermist-dust"
website = "https://www.vermistdust.space"

[console]
loginlocal = false

[build]
fork_id = "VermistDust"

[auth]
mode = 1

[whitelist]
enabled = true

