[log]
path = "logs"
format = "log_%(date)s-%(time)s.txt"
level = 1
enabled = false

[net]
tickrate = 30
port = 1212
bindto = "::,0.0.0.0"
max_connections = 64

[game]
hostname = "Vermist Dust Sector: Central Command"
lobbyenabled = true
soft_max_players = 32
role_timers = false
desc = "[DOWNTIME MODE] Your home away from home."
lobbyduration = 10
defaultpreset = "greenshift"
map = "centcomm"
map_rotation = false
cryo_sleep_rejoining = true

[events]
enabled = false

[ic]
flavor_text = true
restricted_names = false

[ooc]
enable_during_round = true

[looc]
enabled_crit = true

[shuttle]
arrivals_returns = true
auto_call_time = 60
emergency = false
auto_call_time = 0

[infolinks]
github = "https://github.com/vermist-sector/vermist-dust"
website = "https://www.vermistdust.space"

[console]
loginlocal = false

[auth]
mode = 1

[whitelist]
enabled = true
